name: monitoring-system

services:
  db:
    image: postgres
    container_name: bd-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: acceso_rfid
    ports:
      - 6000:5432  # Mapea el puerto interno 5432 de PostgreSQL al 6000 de la máquina
    networks:
      - backend

  php:
    build: .
    container_name: app-container
    ports:
      - 5000:80   # Apache puerto 80 → 5000 de tu máquina/EC2
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_NAME: acceso_rfid

networks:
  frontend: {}
  backend: {}

